#!/bin/bash
# Usage:
#    mkdir test
#    cd test
#    run script
set -e
set -x

if test -z "$1"; then
    echo "$0 <android version>"
    exit 1
fi
ANDROID_VERSION=$1
if test -z "$2"; then
    ANDROID_MANIFEST_FILE=default.xml
else
    ANDROID_MANIFEST_FILE=$2
fi

export SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
repo init -u git://gitorious.org/rowboat/manifest.git -b $ANDROID_VERSION -m $ANDROID_MANIFEST_FILE
#repo init -u git://git.omapzoom.org/platform/omapmanifest -b $ANDROID_VERSION -m $ANDROID_MANIFEST_FILE
(cd .repo/repo; patch -p1 <$SCRIPT_DIR/../data/support_local_repo.patch)
$SCRIPT_DIR/strip-projects.sh .repo/manifest.xml
if test -n "$3"; then
    ln -s $3 .repo/local_manifest.xml
fi
repo sync -n -j 4 && repo sync -l -j 20
unset TARGET_PRODUCT
$SCRIPT_DIR/fixup_common.sh
THISVER=`make -f $SCRIPT_DIR/../data/printvar.mk PLATFORM_VERSION`
echo VERSION `make -f $SCRIPT_DIR/../data/printvar.mk PLATFORM_VERSION` BUILD_ID `make -f $SCRIPT_DIR/../data/printvar.mk BUILD_ID`
(cd $SCRIPT_DIR/../template; tar cf - .) | tar xf -

#setpaths
#Beagleboard Cx
#we have C4
#make TARGET_PRODUCT=3.x
echo "make -j33 TARGET_PRODUCT=beagleboard OMAPES=3.x"
