#!/bin/bash
# Usage:
#    mkdir test
#    cd test
#    run script
set -e
set -x
ANDROID_GENERIC_HOST=${ANDROID_GENERIC_HOST:-https://android.googlesource.com/}
ANDROID_GENERIC_HOST_CODEAURORA=${ANDROID_GENERIC_HOST_CODEAURORA:-git://codeaurora.org}
ANDROID_GENERIC_HOST_OMAPZOOM=${ANDROID_GENERIC_HOST_OMAPZOOM:-git://git.omapzoom.org}

if test -z "$1"; then
    echo "$0 <android version>"
    exit 1
fi
ANDROID_VERSION=$1
if test -z "$2"; then
    ANDROID_MANIFEST_FILE=default.xml
else
    ANDROID_MANIFEST_FILE=$2
fi

export SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
repo init -u $ANDROID_GENERIC_HOST_CODEAURORA/platform/manifest -b $ANDROID_VERSION -m $ANDROID_MANIFEST_FILE
(cd .repo; $SCRIPT_DIR/strip-projects.sh manifest.xml)
if test -n "$3"; then
    ln -s $3 .repo/local_manifest.xml
fi
repo sync -n -j 4 && repo sync -l -j 20
$SCRIPT_DIR/fixup_common.sh
THISVER=`make -f $SCRIPT_DIR/printvar.mk PLATFORM_VERSION`
echo VERSION `make -f $SCRIPT_DIR/printvar.mk PLATFORM_VERSION` BUILD_ID `make -f $SCRIPT_DIR/printvar.mk BUILD_ID`
$SCRIPT_DIR/fixup_$THISVER.sh
(cd $SCRIPT_DIR/template; tar cf - .) | tar xf -

#source build/envsetup.sh; choosecombo 2 msm8960 eng
