#!/bin/bash
set -e
set -x

export SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
#(cd .repo/repo; patch -p1 <$SCRIPT_DIR/../data/support_local_repo.patch)
$SCRIPT_DIR/strip-projects.sh .repo/manifest.xml
if test -n "$3"; then
    ln -s $3 .repo/local_manifest.xml
fi
#repo sync -n -j 4 && repo sync -l -j 20
repo sync
unset TARGET_PRODUCT
$SCRIPT_DIR/fixup_common.sh
THISVER=`make -f $SCRIPT_DIR/../data/printvar.mk PLATFORM_VERSION`
echo VERSION `make -f $SCRIPT_DIR/../data/printvar.mk PLATFORM_VERSION` BUILD_ID `make -f $SCRIPT_DIR/../data/printvar.mk BUILD_ID`
(cd $SCRIPT_DIR/../template; tar cf - .) | tar xf -

echo "source build/envsetup.sh; lunch full_maguro-userdebug"
